node_id: 2

service:
  host: 127.0.0.1
  port: 8099

cron_config:
  single_task_node: 2

jwt_key: jwtkey
callback:
report_host: https://niucube-api.qiniu.com

mysqls:
  - host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    max_idle_conns: 10
    max_open_conns: 100
    database: live
    conn_max_life_time: 5
    default: live

  - host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    max_idle_conns: 10
    max_open_conns: 100
    database: live
    conn_max_life_time: 5
    default: live
    read_only: true