language: go
go:
  - 1.17.x
sudo: true
service:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS live;'
before_script:
  - cd ..
  - export QBOXROOT=`pwd`
  - redis-server --port 6379 --daemonize yes
  - memcached &
script:
  ## pili-pegasus
  - cd $TRAVIS_BUILD_DIR
  - source env.sh
  - make gofmt-check
  - make govet-check
  - make coverage
after_success:
  - cd $TRAVIS_BUILD_DIR
  - bash <(curl -s https://codecov.io/bash) -f $QBOXROOT/coverage.txt -t ${CODECOV_TOKEN}
